#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_ICENGINE_ENABLED
#define AP_ICENGINE_ENABLED 1
#endif

#ifndef AP_AIRMASTER_AC300_ENABLED
#define AP_AIRMASTER_AC300_ENABLED AP_ICENGINE_ENABLED
#endif
