#pragma once

#ifndef AP_GPIO_ENABLED
#define AP_GPIO_ENABLED 1
#endif

#ifndef AP_GPIO_MAX_BACKENDS
#define AP_GPIO_MAX_BACKENDS 2
#endif

#ifndef AP_GPIO_BACKEND_DEFAULT_ENABLED
#define AP_GPIO_BACKEND_DEFAULT_ENABLED AP_GPIO_ENABLED
#endif

#ifndef AP_GPIO_PCA9685_ENABLED
#define AP_GPIO_PCA9685_ENABLED AP_GPIO_BACKEND_DEFAULT_ENABLED
#endif

