#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_MISSION_ENABLED
#define AP_MISSION_ENABLED HAL_GCS_ENABLED
#endif

#ifndef AP_MISSION_NAV_PAYLOAD_PLACE_ENABLED
#define AP_MISSION_NAV_PAYLOAD_PLACE_ENABLED 1
#endif
