#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_MAXON_EPOS4_ENABLED
#define AP_MAXON_EPOS4_ENABLED HAL_PROGRAM_SIZE_LIMIT_KB > 2048
#endif

#ifndef AP_MAXON_EPOS4_MAX_INSTANCES
#define AP_MAXON_EPOS4_MAX_INSTANCES 2
#endif  // AP_MAXON_EPOS4_MAX_INSTANCES
